---
driver:
  name: vagrant

platforms:
- name: ubuntu-15.04
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: debian-8.1
- name: centos-7.1

suites:
- name: user
  run_list: recipe[bashrc_example::user]
- name: system
  run_list: recipe[bashrc_example::system]
